### PR TITLE
fix(curriculum): update to match curriculum challenge instructions

### PR DESCRIPTION
**Pull request by RandellDawson**
This PR makes the same updates to the boilerplate as the current instruction changes on [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/37693) for the curriculum.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM - Hey @scissorsneedfoodtoo, can you take a look at this and the related PR - it would be nice to update them all at the same time (the challenge file, boilerplate, and glitch project) - I don't have access to the glitch account, I'm pretty sure you can make that happen. Thanks.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, thank you for these updates. It's much more clear what learners should do for this step. Also will be nice to get rid of as many error messages as possible.

@moT01, sure, I can make the changes to the Glitch project right away.

**Comment by scissorsneedfoodtoo** [comment]
The updates are now live on Glitch: https://glitch.com/edit/#!/trite-organ?path=myApp.js:15:86

**Comment by RandellDawson** [comment]
How long before the next deployment to production?  Last deployment was over 5 days ago?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, I can't say for sure. @raisedadead would have a better idea of when the next deployment will be.

**Comment by RandellDawson** [comment]
Just checked and the changes are now in production.

**Comment by scissorsneedfoodtoo** [comment]
Great, thank you for confirming that.

**Pull request merged**
