### PR TITLE
cX

### PR DESCRIPTION
**Pull request by storypixel**

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi, this looks like it was opened by mistake, hence the closure.

**Comment by storypixel** [comment]
it was, sorry i got confused while doing the tutorial. really enjoying the
backend material thanks!

**Comment by ojeytonwilliams** [comment]
No worries.  Which bit made you think you needed to create a PR?  You're not the only one, so maybe we need to update the instructions!

**Comment by storypixel** [comment]
it was UI confusion as a result of needing to do 5 steps in order to get a
freecodecamp project imported into codesandbox. here are the current steps
i take and the * marks where i messed up
1. when starting a lesson, I find the 'starter repo' and click on that
2. codesandbox wants a github project to have the 'actual code' on the
master branch for the import function to work... so next i clone the
freecodecamp repo
3. now that the repo is cloned on my account, i'm able to do a PR to put
the "gomix" branch code onto "master" so that i can use it on codesandbox.
i do a PR*
3a. Oh no! I select freecodecamp's master instead of my cloned
repo's master... this was a mistake which lead to this email
4. i do (3) correctly and proceed to import my newly modified clone into
codesandbox
5. finally i'm not allowed to do any changes to this import until i fork it
on codesandbox, which is the last step i do

as you can see it's easy to make a mistake. until codesandbox allows me to
import just a branch or until the main work is on your repos' master
branches, I doubt there is any way to massage the instructions for users
like me.

why do i use codesandbox instead? sadly because i like their vim
keybindings :-P so maybe i deserve this pain lol

**Comment by ojeytonwilliams** [comment]
Thanks for the explanation, that's a big help.  The use of `gomix` as the main branch is no longer necessary, so I think we can move all the boilerplates to `master` and save codesandbox users some pain.

@scissorsneedfoodtoo there weren't any side effects from https://github.com/freeCodeCamp/boilerplate-advancednode/pull/9#issuecomment-618204032 were there?

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, sorry, just seeing this now. No, there weren't any issues moving from `gomix` to `master`, at least as far as I could tell. The only hangup is that we'll need to do this one by one with Mrugesh's help as he seems to be the only one who can adjust the settings for these repos.

**Comment by ojeytonwilliams** [comment]
One other thing that just occurred to me is that the open PRs will need their targets changing.  It should not cause any problems (since `master` will just be a copy of the current `gomix` branch), but it will need doing.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, yes, very true. I figure we'll handle this on a case by case basis. Ideally we'll be able to go through the open PRs, merge them, then flip the main branch to `master` rather than `gomix`.

**Pull request closed without merging**
